# Generated by Django 2.2 on 2019-08-12 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EntryExit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry_exit',
            name='dob',
            field=models.DateField(blank=True, null=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='entry_exit',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
